### ISSUE TITLE
Circular references in AST/G consume the stack

### ISSUE THREAD

**Issue by polkovnikov-ph** [pegjs/website#13] opened 2014-10-10 21:17 UTC
`start = { var a = {}; a.a = a; return a; }`

**Comment by dmajda** [comment] 2015-04-10 13:54
Thanks for your report but this is not a bug of the website but PEG.js itself. It is basically a duplicate of https://github.com/pegjs/pegjs/issues/26 which got recently fixed. Moreover, the test case relies on an empty sequence (the “nothing” between `=` and the action), which is a construct that was [disallowed some time ago](https://github.com/pegjs/pegjs/commit/df154daafb9c6c952351493af02d3a55e0b05c59). These changes will be applied to the online version once PEG.js 0.9.0 is released. Closing.

**Closed by dmajda** 2015-04-10 13:54 UTC
